name: ci

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache
        uses: actions/cache@v2
        with:
          paths:
            - ~/.npm
          key: cache
        env:
          cache-name: npm-cache

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: install packages
        run: npm ci

      - name: run tests
        run: npm test

      - name: upload coverage folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache
        uses: actions/cache@v2
        with:
          paths:
            - ~/.npm
          key: cache
        env:
          cache-name: npm-cache

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: install packages
        run: npm ci

      - name: build
        run: npm run build

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy-to-netlify:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: deploy to netlify
        run: >
          npx netlify deploy
          --prod
          --dir=build
          --message="${{ github.event.commits[0].message }}"
          --site=${{ secrets.NETLIFY_APP }}
          --auth=${{ secrets.NETLIFY_TOKEN }}
