name: deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: install packages
        run: yarn install

      - name: build
        run: yarn build

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy-to-netlify:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: deploy to netlify
        run: >
          npx netlify deploy
          --prod
          --dir=build
          --message="${{ github.event.commits[0].message }}"
          --site=${{ secrets.NETLIFY_APP }}
          --auth=${{ secrets.NETLIFY_TOKEN }}
